## Bayesian inference in a mixture of Gaussians (MoG) model.
##
## Approach: Amortized factorized (mean-field) variational inference.
##
## Reference papers and textbook:
##
## Bishop, Christopher M. (2006).
## "Pattern Recognition and Machine Learning", Springer.
## https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/
##
## Blei, D. M., Kucukelbir, A. and McAuliffe, J. D. (2017).
## "Variational Inference: A Review for Statisticians."
## In "Journal of the American Statistical Association", vol. 112, no. 518, pp. 859–877.
## https://doi.org/10.1080/01621459.2017.1285773
##
## Margossian, C. C. and Blei, D. M. (2024).
## "Amortized Variational Inference: When and Why?"
## In "Proceedings of the Fortieth Conference on Uncertainty in Artificial Intelligence".
## https://proceedings.mlr.press/v244/margossian24a.html
## https://raw.githubusercontent.com/mlresearch/v244/main/assets/margossian24a/margossian24a.pdf


## -------------------------------------------------------------------
## Initialization of parameters.
## -------------------------------------------------------------------


mog_init <- function(model,
  seed, # FIXME passed also through 'args' to var_mog_nw_init
  kmeans_nstart = 10, kmeans_prob = 0.95,
  args = list(),
  debug = TRUE,
  verbose_seed = TRUE)
{
  # Assumes proper elements in 'model' generated by make_model().

  # NOTE Documentation:
  # For type "linear", use for example amortization$init_args = list(sd = 0.01)
  # For type "network", use for example amortization$init_args = list(input_dim = 1, width = 20, output_dim = 1, seed = NULL)
  #
  # linear 'in the parameters', eg. quadratic polynomial cbind(1, x, x^2) is allowed.
  #
  # kmeans_nstart, kmeans_prob: Kmeans initialization of responsibilities
  #   (ignored by var-mog-normal-wishart$init, see next argument).
  #
  # args: further arguments to be passed to the family initializer
  #   (currently only required for var-mog-normal-wishart$init).

  am <- model$amortization

  if (length(args) && !startsWith(model$family, "var_"))
  {
    args <- list()
    warning("Argument 'args' was ignored. It applies only for VAR-MoG models.")
  }

  # The seed is used only for model var-mog or when kmeans fails.
  # The seed may not be used, but this is done here to keep
  # the code below simple.
  #
  # NOTE kmeans randomly selects initial centers (we use centers=K)
  # FIXME this may require updating when amortization$finit is used.

  if (verbose_seed)
  {
    # FIXME simplify as in em_init_resp().

    msg_seed <- if (missing(seed) && is.null(am$features))
      paste("K-means failed. Random initialization of responsibilities.",
             "System's seed was used (not reproducible).") else ""

    if (is.null(args$seed))
    {
      # FIXME check that in this case the seed is not used elsewhere, i.e. the same seed is not used twice,
      # because argument 'seed' is intended to be used only in the event that kmeans fails,
      # args$seed is the seed for VAR-MoG, in which case the block for kmeans in this function does not apply

      #if (model$family == 'var_mog_normal_wishart')
      if (startsWith(model$family, 'var_'))
      {
        msg <- "System's seed was used (not reproducible)."

        if (!missing(seed))
          msg <- paste(msg, "Argument 'seed' was ignored.",
            "For model 'var_mog' set the seed through argument args=list(seed).")

        warning(msg)

      } else
      #if (model$family == 'var_mog_normal_wishart')
      if (startsWith(model$family, 'var_'))
        warning(paste("System's seed was used (not reproducible).",
          "For model 'var_mog' the seed may be set through argument args=list(seed)."))

    } else { # !is.null(args$seed)
      # FIXME double-check the same as the comment above, in this case argument 'seed' is not used
      if (!missing(seed))
      {
        if (startsWith(model$family, 'var_'))
          warning("Argument 'seed' was ignored. 'args$seed' was used.")
      } # else, missing(seed) handled in message above
    }
  } else msg_seed <- ""

  #family <- model$family
  family <- get(model$family)

  X <- model$X
  Xlags <- model$Xlags
  K <- model$K
  D <- model$D
  N <- model$N

  # -------------------------------------------------------------------
  # Parameters of prior densities.
  #
  # Further initialization is done for model VAR-MoG:
  #   rprobs and pars.
  # -------------------------------------------------------------------

  # NOTE documentation:
  # for MoG models family$init sticks to set prior parameters;
  # for VAR-MoG models rprobs and pars are also initializated.

  model <- do.call(family$init, c(list(model = model), args))
  #tmp <- do.call(family$init, c(list(model = model), args))
  #priors <- tmp$priors #[[1]]
  #rprobs <- tmp$rprobs #[[2]]
  #pars <- tmp$pars #[[3]]

  # -------------------------------------------------------------------
  # Responsibilities.
  #
  # If amortization is applied:
  #   The parameters of the amortization function are initialized instead.
  #   The responsibilities inferred by the amortization are then computed.
  # -------------------------------------------------------------------

  # NOTE documentation:
  # In a previous version responsibilities were initialized after initializing
  # the remaining parameters by means of the CAVI update of the responsibilities.
  # The CAVI update avoids random initialization of the N x K matrix.
  # Here, the opposite is applied: Responsibilities are first initialized and
  # then the remaining parameters are initialized according to CAVI updates
  # (keeping all the parameters coherent with each other, as before).
  # Initialization of responsibilities is now based on k-means. It is therefore
  # an informed initialization.
  # If k-means fails, then random initialization is applied.

  if (is.null(am$features))
  {
    if (is.null(model$rprobs))
    {
      # NOTE Documentation:
      # This design is suitable for different approaches to initialization;
      # the init function of a new family can be simplified by
      # letting mog_init() to initialize 'rprobs' here.
      # family$init may also create 'rprobs'; if so, this block is not applied.

      rprobs_was_null <- TRUE

      km <- try(kmeans(X, centers = K, nstart = kmeans_nstart), silent = TRUE)

      if (inherits(km, "try-error"))
      {
        # warning("K-means failed. Random initialization of responsibilities was applied.")
        if (!is.null(seed)) set.seed(seed)
        if (msg_seed != "") warning(msg_seed)

        rprobs <- softmax_rows(matrix(rnorm(N * K), N, K))

      } else {
        # NOTE K=1 is not expected.
        rprobs <- matrix((1 - kmeans_prob) / (K - 1), N, K)
        rprobs[cbind(seq_len(N), km$cluster)] <- kmeans_prob
      }

    } else { # !is.null(model$rprobs)
      # rprobs was initialized above by family$init (var_mog_normal_wishart).
      rprobs_was_null <- FALSE
    }

    # The parameters of the amortization function
    # need not be initialized in this case.
    etas <- NULL

  } else { # !is.null(am$features)

    # NOTE Documentation:
    #   was not NULL, or actually it was recomputed (see what variable name is clearer).
    # if not null rprobs give warning ignored (recomputed for the model specification above)
    rprobs_was_null <- TRUE

    # -------------------------------------------------------------------
    # Initialize etas: Array of dimension ncol(am$features) x K
    # containing the coefficients of the inference function (amortization map).
    # Generate small random coefficients.
    # -------------------------------------------------------------------

    # Currently amortization can be considered for the scores of the
    # variational responsibilities.
    # We just need K-1 coefficients because when they are multiplied
    # by amortization$features, softmax_rows() normalization is applied,
    # so one of them can be inferred simply as 1 - ().
    #
    # Normalization implies therefore that one of the coefficients may
    # be excluded from the set of free parameters passed to stats::optim().
    # (Recall that in general the amortization approach requires numerical
    # optimization rather than relying on closed-form CAVI updates.)

    if (is.null(am$fn)) # "linear" amortization function by default
    {
      # By default apply a function linear in the parameters
      # (the features can be quadratic terms, ...).
      # amortization$finit (if defined) is ignored.
      #
      # linear in the parameters, so see do a linear regression:
      # etas <- rnorm(ncol(amortization$features) * K)
      # etas <- .lm.fit(x = amortization$features, y = X, tol = 1e-7)$coef
      # rprobs <- softmax_rows(as.vector(amortization$features %*% eta))

      # rprobs <- softmax_rows(stats::fitted(stats::lm(X ~ 0 + amortization$features)))

      #FIXME do this using lighter version stats::.lm.fit().

      #FIXME See do as above check try-error; otherwise random initialization.

#FIXME check dimensions.

      # FIXME see alternative to rnorm(), lm, ...
      #etas <- .lm.fit(x = amortization$features, y = X, tol = 1e-7)$coef

      # NOTE The seed is not set again, the set.seed(seed) called above
      # belongs to a mutually exclusive condition (is.null(am$features)).
      if (!is.null(seed))
        set.seed(seed)

      etas_nr <- NCOL(am$features)
      etas <- do.call("rnorm", c(list(n = etas_nr * (K - 1)), am$init_args))
      etas <- matrix(etas, etas_nr, K - 1)

    } else { # !is.null(amortization$fn)

      #etas <- init_network(input_dim = 1, width = 20, output_dim = 1, seed = NULL)
      #etas <- do.call("init_network", amortization$args)

      if (is.null(am$finit))
        stop("amortization$features is not NULL, but 'amortization$finit' is not defined (use for example 'init_network').")

      # FIXME If seed is defined as argument, the same seed is used for each etas_k.

      #for (i in seq_len(K - 1)) do.call("init_network", am$args)
      etas <- replicate(K - 1,
        do.call(am$finit, am$init_args), simplify = FALSE)
        #do.call("init_network", am$init_args), simplify = FALSE)

      #e.g.: amortization$fn = "forward_network"
    }

    # mog_rprobs_from_amortization() handles NULL amortization$fn
    # applying a linear function fn = function(X, etas) X %*% etas),
    # consistent with the block above.

    rprobs <- mog_rprobs_from_amortization(etas, am, debug)

  } # end # !is.null(amortization$features)

  if (rprobs_was_null) # rprobs was created above
  {
    if (debug)
    {
      # this is checked twice if the branch that class mog_rprobs_from_amortization() is used above
      stopifnot(all.equal(unname(rowSums(rprobs)), rep(1, N)))
      #stopifnot(!any(rprobs < 0))
      if (any(rprobs < 1e-12))
        warning("Responsibilities are non-negative, but some turned lower than 1e-12.")
    }

    # model update required here, before running update() in var_mog model
    model$rprobs <- rprobs
  }

  # -------------------------------------------------------------------
  # Initialize the remaining parameters using
  # CAVI updates given the responsibilities initialized above.
  # -------------------------------------------------------------------

  #init <- family$update(X, rprobs, ipars$priors_pars, K, D, Xlags, ipars$pars)
  #pars <- family$update(X, rprobs, priors_pars, K, D, Xlags, pars)
  model$pars <- family$update(model)

  #model$priors <- priors
  model$etas <- etas # safe to set it here, not required above by pars update

  model
}


## -------------------------------------------------------------------
## Evidence lower bound (ELBO) for the MoG model.
## Analytical ELBO.
## -------------------------------------------------------------------

mog_elbo <- function(model, do_rprobs = TRUE, debug = TRUE)
{
  # Assumes proper elements in 'model' generated by make_model() and mog2_init().

  # NOTE Documentation:
  # 'do_rprobs' is ignored if amortization$features is null.
  #
  # FIXME see if do_rprobs is actually needed; it is required for the hybrid approach
  # but maybe better do within CAVI rather than here, where we may assume consistency
  # between etas, rprobs and pars.
  # See do mog_rprobs_from_amortization() within init().

  family <- get(model$family)

  etas <- model$etas
  am <- model$amortization

  if (!is.null(am$features) && do_rprobs)
  {
    # This update is required when called by the hybrid mog_cavi_amortized(),
    # i.e. when optimal neural-network amortization parameters are searched
    # numerically by means of optim().

    rprobs <- mog_rprobs_from_amortization(etas, am, debug)

    # Update the remaining parameters.
    # Keep consistency of the parameters with the latest responsibilities.

    model$pars <- family$update(model)

    # In the future some 'pars' could be 'fixed', if so do:
    # new_pars <- family$update(model)
    # pars[names(new_pars)] <- new_pars
  }

  family$elbo(model, debug)
}


## -------------------------------------------------------------------
## Coordinate-ascent variational inference (CAVI).
## Coordinate-wise maximization of the ELBO in an MoG model.
## -------------------------------------------------------------------

mog_cavi <- function(model,
  maxiter = 500, tol = 1e-8,
  verbose = TRUE, debug = FALSE)
{
  # Assumes proper definition of argument 'model',
  # generated by make_model() and initialized by mog_init().

  family_name <- model$family
  family <- get(model$family)

  # Storage.

  elbo_path <- rep(NA, maxiter + 1)
  elbo <- mog_elbo(model, list(features = NULL), debug)
  elbo_path[1] <- if (debug) elbo$elbo else elbo

  # Main loop.

  converged <- FALSE
  niter <- 0

  for (iter in seq_len(maxiter))
  {
    # Update variational responsibilities.

    model$rprobs <- family$resp_update(model, debug)

    # Update remaining variational parameters.

    model$pars <- family$update(model)

    # Check convergence and trace iterations.

    elbo <- mog_elbo(model, list(features = NULL), debug)

    elbo_path[iter+1] <- if (debug) elbo$elbo else elbo

    if (verbose)
    {
      # FIXME TODO init$pars$mu_ms does not apply to VAR model, trace instead max(abs(init$pars$Bbar)), max(abs(init$pars$m).
      #cat(sprintf("iter = %4d | ELBO = %.6f | max mu = %.4f\n",
      #  iter, elbo_path[iter+1], max(abs(init$pars$mu_ms))))
      cat(sprintf("iter = %4d | ELBO = %.6f\n", iter, elbo_path[iter + 1]))
    }

    rel_change <- abs(elbo_path[iter+1] - elbo_path[iter]) / (1 + abs(elbo_path[iter]))

    niter <- iter

    #if (rel_change < tol && is.finite(rel_change))
    # This order avoids error if rel_change is NA.
    if (is.finite(rel_change) && rel_change < tol)
    {
      converged <- TRUE
      break
    }

  } # end main loop

  # Estimated posteriors summary (means).

  posteriors <- family$posteriors(model)

  # FIXME see include 'posteriors' within 'model' or as a separate element;
  # within model may create too many inner lists

  res <- list(model = model, posteriors = posteriors,
    elbo_path = elbo_path[seq_len(niter + 1)],
    converged = converged, niter = niter)
  class(res) <- paste0(family_name, "_cavi") #"mog_cavi"
  res
}


## -------------------------------------------------------------------
## Amortized coordinate-ascent variational inference (CAVI).
##
## Hybrid optimization approach:
## The parameters of the amortization function are updated by numerical optimization.
## Then, CAVI closed-form equations are used to update the remaining parameters.
##
## Numerical optimization for the entire set of parameters would require
## imposing restrictions to some parameters. The hybrid approach makes
## use of available closed-form expressions and ensures positive definiteness
## of precision matrices, as well as proper parameters for the
## Gaussian-Wishart (dof > D-1, beta_k > 0).
## -------------------------------------------------------------------

# -------------------------------------------------------------------
# Compute responsibilities inferred by the amortization function.
# -------------------------------------------------------------------

mog_rprobs_from_amortization <- function(etas,
  amortization = list(features = NULL, fn = NULL, args_fn = list()), debug = TRUE)
{
  # NOTE The arguments are collected in a list for convenience;
  # this helps organizing the arguments of other functions (mog_init, mog_elbo).
  # Extracting the arguments once at the beginning may reduce overhead,
  # compared to calling several times to amortization$arg.

  features <- amortization$features
  fn <- amortization$fn
  args <- amortization$args_fn

  if (is.matrix(etas))
  {
    #FIXME use this approach in init(),
    # where null fn forces linear function and is.matrix(fn) ignores the definition of fn

    Metas <- cbind(0, etas)

    # By default use a linear amortization function.
    # Linear in the parameters (a quadratic polynomial cbind(1,x,x^2) is allowed).
    if (is.null(fn))
      fn <- function(X, etas) X %*% etas

    rprobs <- softmax_rows(do.call(fn,
        c(list(X = features, etas = Metas), args)))

  } else
  if (is.list(etas))
  {
    # Neural-network amortization function.

    R <- length(etas) + 1L
    Maux <- matrix(0.0, nrow(features), R)

    for (r in seq_len(R - 1))
      Maux[,r+1] <- do.call(fn,
        c(list(X = features, etas = etas[[r]]), args))$Y

    rprobs <- softmax_rows(Maux)

  } else
    stop(sprintf("Unexpected class of argument 'etas': %s.", class(etas)))

  if (debug)
  {
    if (!all(abs(rowSums(rprobs) - 1) < .Machine$double.eps^0.8))
      stop("Responsibilities do not add up to one for some point.")
    if (any(rprobs < -1e-12)) stop("Some responsibilities turned non-negative.")
    #if (nrow(rprobs) != N) stop("Wrong number of rows in responsibilities.")
    #if (ncol(rprobs) != K) stop("Wrong number of columns in responsibilities.")
  }

  rprobs
}

# -------------------------------------------------------------------
# Hybrid CAVI.
# Numerical optimization of amortization parameters and
# CAVI updates for the remaining parameters.
# -------------------------------------------------------------------

mog_cavi_amortized <- function(model,
  optim_args = list(method = "BFGS", hessian = FALSE),
  debug = FALSE)
{
  # Assumes proper elements in 'model' created by the functions above,
  # make_model(), mog_init(), ...

  # NOTE For future: vec_to_list() allows transformation of parameters,
  # currently not used.

  # FIXME see do verbose argument as in mog_cavi().

  fn <- function(vec_etas)
  {
    #model$etas <- vec_to_list(vec_etas, list(etas = model_struct$etas))
    model$etas <- vec_to_list(vec_etas, etas_struct)

    #val <- mog_elbo(model, do_rprobs, FALSE)
    model$rprobs <- mog_rprobs_from_amortization(model$etas, model$amortization, FALSE)
    model$pars <- family$update(model)
    val <- mog_elbo(model, FALSE, FALSE)

    if (!is.finite(val))
      return(.Machine$double.xmax)
    -val
  }

  do_rprobs <- TRUE

  family <- get(model$family)
  family_name <- model$family

  etas <- model$etas
  etas_struct <- get_pars_structure(etas)
  vec_etas <- if (is.list(etas)) unlist(etas) else as.vector(etas)

  opt <- do.call("optim", c(list(par = vec_etas, fn = fn), optim_args))

  # Final parameters and ELBO evaluation.

  etas <- vec_to_list(opt$par, etas_struct)
  rprobs <- mog_rprobs_from_amortization(etas, model$amortization, debug)

  model$etas <- etas
  model$rprobs <- rprobs

  model$pars <- family$update(model)

  elbo <- mog_elbo(model, FALSE, FALSE)

  # Estimated posteriors summary (means).

  posteriors <- family$posteriors(model)

  # FIXME see include 'posteriors' within 'model' or as a separate element;
  # within model may create too many inner lists

  res <- list(optim = opt, elbo = elbo, model = model, posteriors = posteriors)
  #class(res) <- paste0(family_name, "_acavi") #"mog_acavi"
  class(res) <- "acavi"
  res
}

print.acavi <- function(x, digits = 4, ...)
{
  #class_x <- class(x)
  #if (substr(class_x, nchar(class_x) - 5, nchar(class_x)) != "_acavi")
  #  stop("'x' must be an object of class 'xxx_acavi'.")
  if (!inherits(x, "acavi")) {
    stop("'x' must be an object of class 'acavi'.")
  }

  y <- x
  class(y) <- paste0(x$model$family, "_cavi")

  # FIXME make it clear in the output; documentation: optim code (not TRUE/FALSE).
  y$converged <- x$optim$convergence
  # FIXME (function and gradient counts, not explicit in the printed output)
  y$niter <- x$optim$counts
  y$elbo_path <- NULL

  print(y)

  cat("Final ELBO:", round(x$elbo, digits), "\n")

  cat("\nAmortization function parameters.\n")
  cat("----------------------------------------------------------------\n")

  if (is.matrix(x$model$etas)) {
    print(round(x$model$etas, digits))
  } else{
    n_am_pars <- length(flatten_pars(x$model$etas))
    if (n_am_pars > 20) {
      cat("The number of amortization parameters is too large to be printed:", n_am_pars, ".\n")
      cat("Inspect 'x$model$etas'.\n")
    } else {
      #cat("Inspect 'x$model$etas'; contains", n_am_pars, "parameters. \n")
      invisible(lapply(x$model$etas, function(x) print(round(x, digits))))
    }
  }
}
